src/main/java/com/mycila/maven/plugin/license/AbstractLicenseMojo.java
src/main/java/com/mycila/maven/plugin/license/Callback.java
src/main/java/com/mycila/maven/plugin/license/LicenseCheckMojo.java
src/main/java/com/mycila/maven/plugin/license/LicenseFormatMojo.java
src/main/java/com/mycila/maven/plugin/license/LicenseRemoveMojo.java
src/main/java/com/mycila/maven/plugin/license/document/DocumentType.java
src/test/java/com/mycila/maven/plugin/license/MappingMojoTest.java
src/test/java/com/mycila/maven/plugin/license/UseDefaultMappingMojoTest.java
src/test/resources/check/Dockerfile
src/test/resources/extensionless/header.txt
src/test/resources/unknown/header.txt

The motivation for this change is to introduce an option that makes it impossible that there are license-header-less files left in the projects.
From the failIfUnknown JavaDoc:
> You can leave this flag on `false` if you do not want the build to fail for files that do not have an implicit or explicit comment style definition. Setting this explicitly to `true` is a safe way to make sure that the effective file type mappings cover all files included from your project.

Add the failIfUnknown option

---

README.md

I assume it's Apache license, as that's what the [parent says](https://github.com/mycila/pom/blob/master/pom.xml#L83).

Clarify license of license-maven-plugin (!)

---

license-maven-plugin-git/src/main/resources/META-INF/services/com.mycila.maven.plugin.license.PropertiesProvider

Trying to use the license-maven-plugin-git for the first time, I found out that the service file is missing :(

Add service file for CopyrightRangeProvider

---

license-maven-plugin/src/main/resources/com/mycila/maven/plugin/license/templates/UNLICENSE.txt

The UNLICENSE seems to be a popular choice for people in order to release their work into the public domain. The GitHub license picker supports it as well.
See http://unlicense.org for more details.

Add UNLICENSE template file

---

license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/RemoveMojoTest.java
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/UpdateMojoTest.java

usage of platform line-separator in some tests where it make sense
now with tests running also on windows real re-factoring & contributions can start

fixes #70, temporary correction that makes tests to pass even under windows

---

license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/AbstractLicenseMojo.java

47fe9729 changed the default value of license.strictCheck to "true",
but the javadoc still described the default as "false".

Fix the javadoc text to match the actual code

---

license-maven-plugin/src/main/resources/com/mycila/maven/plugin/license/templates/APACHE-2.txt

The current Apache License, Version 2.0 has two tabs (8 spaces). But the officiel Apache License, Version 2.0 has one tab (4 spaces); http://www.apache.org/licenses/LICENSE-2.0.html#apply

Changed the double tab to one tab

---

license-maven-plugin/src/main/resources/com/mycila/maven/plugin/license/templates/AGPL-3.txt
license-maven-plugin/src/main/resources/com/mycila/maven/plugin/license/templates/APACHE-2.txt
license-maven-plugin/src/main/resources/com/mycila/maven/plugin/license/templates/CPAL.txt
license-maven-plugin/src/main/resources/com/mycila/maven/plugin/license/templates/GPL-3.txt
license-maven-plugin/src/main/resources/com/mycila/maven/plugin/license/templates/LGPL-3.txt
license-maven-plugin/src/main/resources/com/mycila/maven/plugin/license/templates/MIT.txt
license-maven-plugin/src/main/resources/com/mycila/maven/plugin/license/templates/MPL-2.txt

- (c) and (C) were both converted to ©
- '${project.name}' was replaced w/ 'This program'
- GPL licences got their proper introduction
See https://www.gnu.org/licenses/gpl-3.0.html and https://www.gnu.org/licenses/gpl-howto.html for information about how to use GPL licences.

Issue #41 - Fix license templates

---

license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/AbstractLicenseMojo.java
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/MappingMojoTest.java
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/QuietMojoTest.java
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/UpdateMojoTest.java
license-maven-plugin/src/test/resources/check/issue107/header.txt
license-maven-plugin/src/test/resources/check/issue107/test.xml.tmpl
license-maven-plugin/src/test/resources/check/test.xml.tmpl

PR for issue #107. The issue was found in latest and on v2.11 (probably in previous versions, too.)

Investigate mapping ordering

---

README.md
license-maven-plugin/src/main/resources/com/mycila/maven/plugin/license/templates/MirOS.txt

This is actually a Free Software licence and OSI certified.
This is part 1; part 2 would be to actually list all relevant copyright years,
and not a range (dash-delimited — actually ‘–’-delimited (en dash),
not ‘-’-delimited (hyphen-minus)) either, but that’s still open:
https://github.com/mycila/license-maven-plugin/issues/95

Add The MirOS Licence

---

README.md
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/header/HeaderType.java
license-maven-plugin/src/test/resources/styles/javapkg_style.txt

Closes: https://github.com/mycila/license-maven-plugin/issues/38

add JAVAPKG_STYLE to supplant JAVADOC_STYLE, don’t bind by default

---

license-maven-plugin-git/src/main/java/com/mycila/maven/plugin/license/git/CopyrightRangeProvider.java
license-maven-plugin-git/src/main/java/com/mycila/maven/plugin/license/git/GitLookup.java
license-maven-plugin-git/src/test/java/com/mycila/maven/plugin/license/git/CopyrightRangeProviderTest.java
license-maven-plugin-git/src/test/java/com/mycila/maven/plugin/license/git/GitLookupTest.java

Reason behind this PR:
Sometimes you are required to include in your license header only the
date of the file creation.
These changes allow us to look at the git history and find the year of
reation for a given file.
Note:
Sometimes git is unable to figure out the date of creation of a file if
this has moved/renamed without git being able to detect such change.
A potential future solution could be to avoid dates to be overwritten.
I would leave that for another PR though.
Additionally, this PR reduces a bit of duplicated code in the git plugin.

Track the year of a file creation through license-maven-plugin-git

---

license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/AbstractLicenseMojo.java

Add a parameter to specify an absolute value of threads to start.
For the rational please see https://github.com/mycila/license-maven-plugin/pull/132
Please choose either #132 or this PR, they are orthogonal and this PR includes also the fix of #132.
Replaces https://github.com/mycila/license-maven-plugin/pull/133.

feature: Add a `numberThreads` parameter.

---

README.md
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/AbstractLicenseMojo.java
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/Multi.java
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/header/HeaderSource.java
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/util/FileUtils.java
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/HeaderMojoTest.java
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/header/HeaderSourceTest.java
license-maven-plugin/src/test/resources/alternative-single-line-header.txt

This adds support for source-code projects that use [multi-licensing](https://en.wikipedia.org/wiki/Multi-licensing) (e.g. dual-licensing).
If your source code makes use of multi-licensing, then instead of
a `<header>` or `<inlineHeader>` element in the configuration
you can use a `<multi>` element.
The `<multi>` element allows you to specify an optional preamble,
one or more header (or inlineHeader) and separators between them. These
options are concatenated together to produce a header template.
```xml
<plugin>
<groupId>com.mycila</groupId>
<artifactId>license-maven-plugin</artifactId>
<version>X.Y.ga</version>
<configuration>
<multi>
<preamble><![CDATA[This product is dual-licensed under both the GPLv2 and Apache 2.0 License.]]></preamble>
<header>GPL-2.txt</header> …
```

Plugin configuration to support multi-licensing scenarios

---

license-maven-plugin-git/src/main/java/com/mycila/maven/plugin/license/git/CopyrightAuthorProvider.java
license-maven-plugin-git/src/main/java/com/mycila/maven/plugin/license/git/GitLookup.java
license-maven-plugin-git/src/main/java/com/mycila/maven/plugin/license/git/GitPropertiesProvider.java
license-maven-plugin-git/src/main/resources/META-INF/services/com.mycila.maven.plugin.license.PropertiesProvider
license-maven-plugin-git/src/test/java/com/mycila/maven/plugin/license/git/CopyrightAuthorProviderTest.java

Hi, I'm a user of your license maven plugin and git plugin.
I wanted to insert original author name and email address into license headers using git history,
so I made following patch for git plugin:
- added CopyrightAuthorProvider to treat author  information of first commit
- modified GitLookup.java to obtain author information from git history
- separated getGitLookup method from  CopyrightRangeProvider to GitPropertiesProvider base class.
- added unit test of CopyrightAuthorProvider
Could you review this PR when you're available?
Thank you.

added provider of author name and email address obtained from first commit

---

license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/Default.java

Adds support to exclude CI config files by default for:
* GitHub Actions
* AppVeyor
* CircleCI
* SourceHut

Update default excludes for further CIs

---

license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/AbstractLicenseMojo.java

A very simple change to allow you to specify `-Dlicense.excludes` or `-Dlicense.includes` on the command line to `mvn license:check` or `mvn license:format`.

Allow include and exclude paths to be overridden with user properties

---

license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/Multi.java

I found this issue whilst writing integration tests. The unit tests that are present don't necessarily catch this. The integration tests will be supplied as part of the licenseSet PR.

Make sure multi-license parameters are correctly set by Maven

---

.travis.yml
license-maven-plugin/pom.xml
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/AbstractLicenseMojo.java
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/util/Selection.java
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/util/SelectionTest.java

If any inclusion is "**anything" then DirectoryScanner will browse excluded folders. It completely defeats most of exclusions and typically let the plugin go through target and node_modules which can be very time consuming.
With this patch, my license check (only) went from 25s to 2.5s.

ensure exclusions win over inclusions for scanning

---

pom.xml

When the parent is not physicaly part of a project, its imporant to force project to look to .m2 cache.  Otherwise it will throw warnings if there is a pom up one directory that is not for this project.

[pom] Make project look into .m2/cache for mycila-pom as not part of this project

---

.travis.yml
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/AbstractLicenseMojo.java
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/util/FileUtils.java
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/util/resource/ResourceFinder.java
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/header/HeaderSourceTest.java
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/util/SelectionTest.java
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/util/resource/ResourceFinderTest.java
pom.xml

* Minimum is now Java 8
* Travis CI now tests for Java 8 on:
* Linux (Ubuntu - Xenial)
* macOS (10.13)
* Windows

Java 8 and Linux/macos/Windows targets for Travis

---

license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/document/DocumentType.java

SCSS is similar to CSS thus JAVADOC_STYLE
WSDL/XSTL are xml based and XML_STYLE

Add additional known document types: SCSS, WSDL, XSTL

---

license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/Default.java
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/DefaultTest.java

Jenkinsfile is intended to be checked into SCM. As such it should contain a license just like any other source file.
https://www.jenkins.io/doc/book/pipeline/jenkinsfile/

Jenkinsfile is source code

---

README.md
license-maven-plugin/src/it/pom-properties/invoker.properties
license-maven-plugin/src/it/pom-properties/mock-license.txt
license-maven-plugin/src/it/pom-properties/pom.xml
license-maven-plugin/src/it/pom-properties/setup.groovy
license-maven-plugin/src/it/pom-properties/src/main/java/com/mycilla/it/Unformatted1.java
license-maven-plugin/src/it/pom-properties/src/main/java/com/mycilla/it/Unformatted1.java.expected
license-maven-plugin/src/it/pom-properties/verify.groovy
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/AbstractLicenseMojo.java

Also includes IT testing all current supported pom properties

POM Project Organization properties

---

license-maven-plugin/pom.xml
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/AbstractLicenseMojo.java
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/LicenseCheckMojo.java
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/dependencies/AbstractLicensePolicyEnforcer.java
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/dependencies/AggregateLicensePolicyEnforcer.java
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/dependencies/ArtifactLicensePolicyEnforcer.java
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/dependencies/DefaultLicensePolicyEnforcer.java
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/dependencies/LicenseMap.java
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/dependencies/LicenseMessage.java
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/dependencies/LicenseNameLicensePolicyEnforcer.java
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/dependencies/LicensePolicy.java
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/dependencies/LicensePolicyEnforcer.java
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/dependencies/LicensePolicyEnforcerResult.java
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/dependencies/LicenseURLLicensePolicyEnforcer.java
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/dependencies/MavenProjectLicenses.java
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/CheckTest.java
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/dependencies/AggregateLicensePolicyEnforcerTest.java
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/dependencies/ArtifactLicensePolicyEnforcerTest.java
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/dependencies/ArtifactLicensePolicyEnforcerTestBase.java
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/dependencies/LicenseNameLicensePolicyEnforcerTest.java
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/dependencies/LicensePolicyEnforcerResultTest.java
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/dependencies/LicensePolicyTest.java
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/dependencies/LicenseURLLicensePolicyEnforcerTest.java
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/dependencies/MavenProjectLicensesIT.java
license-maven-plugin/src/test/resources/config/approve/pom.xml
license-maven-plugin/src/test/resources/config/deny/pom.xml
license-maven-plugin/src/test/resources/config/null/pom.xml
pom.xml

Sorry for the massive PR, the complexity of #203 eluded me and I just kept coding, should have circled back a few times with you first @mathieucarbou .
Some overview:
* this code meets my immediate needs within my company, so I consider it ready to merge (sans any feedback changes you have me make)
* everything is implemented within the same `check` goal, however I've setup my integration tests and primary classes to support a `report` goal which we can do in a separate review
* I deviated slightly from this project's current maven-invoker-plugin approach to running integration tests. I wanted a few primary cases to be covered outside my unit tests, and the invoker method was really slow and impossible to debug, so I'm `org.apache.maven.it.Verifier` within junit to execute integration …

license policy enforcement with maven project implementation.

---

README.md
src/site/markdown/dependency-enforcement.md
src/site/site.xml

Some documentation on the license enforcement feature. I've linked it from the main readme, but in a location that would support a maven site, see my related pr to your parent pom here: https://github.com/mathieucarbou/parent-pom/pull/6

add a readme on dependency enforcement usage

---

license-maven-plugin-git/src/main/java/com/mycila/maven/plugin/license/git/CopyrightRangeProvider.java
license-maven-plugin-git/src/main/java/com/mycila/maven/plugin/license/git/GitLookup.java
license-maven-plugin-git/src/test/java/com/mycila/maven/plugin/license/git/CopyrightRangeProviderTest.java

For some Copyright policies the years in the header should reflect only
the existence of that file not the project as a whole.  While this can
be achieved by using `${license.git.copyrightCreationYear}` and
`${license.git.copyrightLastYear}` in the header template you end up
generating awkward headers for some files e.g. `2021-2021`.  And you
cannot use `${license.git.copyrightYears}` for this use case because that
will use the project inception year giving you something like `2019-2021`.
This commit adds a new calculated property
`${license.git.copyrightExistenceYears}` which provides this information
and may be used in header templates where this behaviour is desired.  This
should basically address the issue described in adobe/S3Mock#241 
It also fixes a bug in `GitLookup` whereby if …

Support injecting Copyright Years based on file existence

---

pom.xml

This must always be set if the folder above is not part of same project.  This causes it to throw warnings if broader project attached, just wastes a check and ultimately it should be looking in the caching system and remote instead.

[pom] Fix relative path

---

.github/workflows/snapshot-report.yml

Preventing the site update from running on forks.

[github] Only run snapshot-report from mathieucarbou

---

license-maven-plugin-git/src/main/java/com/mycila/maven/plugin/license/git/GitLookup.java

The `Git` class implements `AutoCloseable` which triggers warnings that the resource is not closed.  
However, the `close()` method documents that closure of the underlying repo does not occur with this particular usage and would be a no-op.  Adding a suppress warning notation helps indicate that we (think we) know what we're (not) doing.

Suppress resource leak warning for instantiated Git object

---

license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/util/FileUtils.java

~`FileChannel` is not `Closeable`,~ (actually it is) ~so including it in a try-with-resources block does not close the underling streams.  Refactored to ensure the closeable object is referenced in try.~
Also implemented a try-with-resources block for the `BufferedReader` closure.

Suppress resource leaks warnings in FileUtils

---

license-maven-plugin/pom.xml
pom.xml

- added two that need to be provided that are compile in usage.  This is now required upon backport to maven plugin plugin that throws warnings to the same.  These specific libraries ship with maven and therefore are not needed to repeat.  This keeps m2 repository cleaner.

[pom] Per maven standards, make certain artifacts provided

---

license-maven-plugin-git/pom.xml
license-maven-plugin-git/src/test/java/com/mycila/maven/plugin/license/git/CopyrightAuthorProviderTest.java
license-maven-plugin-git/src/test/java/com/mycila/maven/plugin/license/git/CopyrightRangeProviderTest.java
license-maven-plugin-git/src/test/java/com/mycila/maven/plugin/license/git/GitLookupTest.java
license-maven-plugin-svn/pom.xml
license-maven-plugin/pom.xml
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/CompleteMojoTest.java
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/header/DefaultHeaderDefinitionTest.java
pom.xml

This resolves shortcoming in junit 5 migration.  I had initially wrote that code months ago and coming back to it only ran on command line.  Outside of missing import changes in a few spots at that time, it appeared my work was done.  However, the jump to junit 5 resulted in command line tests no longer running which then highlighted this was not complete on a small number of tests.  To ensure this type of thing never happens again, I've added jacoco to the mix.  Each pom has jacoco coverage number set.  The top one which is just pom is set to 100% for clarity reasons.  The other three are set to their appropriate current code coverage (git module 81%, svn module has no tests, and main plugin at 77%).  The svn module didn't actually need the setting as jacoco is skipped when no tests but …

Restore test runs, add jacoco, and fix resulting broken tests

---

.mvn/checkstyle.xml
pom.xml

The checkstyle file is identical to google's from the checkstyle jar with this project license header added as at least at the moment was required but probably should be ignored.
Reason for using the file directly is that there is some expectation of changes needed.  I forsee at least 100 characters per line being set to 120 for more reasonable usage.  There could be others so starting there helps.  Do note that means that with any update on checkstyle, given they do not use semantic versioning there is little backwards compatibility even at minor revisions.  Therefore, its entirely possible it fails fast when updated as it does with 10.0 already.  Thus for any upgrades, its important to extract the content and overlay it reapplying any custom changes that occur later.  Typically that is …

[pom] Add checkstyle with last jdk < 11 usage at 9.3 and basic setup

---

docs/index.md
license-maven-plugin-git/README.md
license-maven-plugin-git/src/main/java/com/mycila/maven/plugin/license/git/GitLookup.java
license-maven-plugin-git/src/test/java/com/mycila/maven/plugin/license/git/GitLookupTest.java

Hey @mathieucarbou ,
here is the PR, thanks for your consideration.
Kind regards, 
Philipp

Add feature to ignore git commits by id

---

license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/dependencies/MavenProjectLicenses.java
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/dependencies/MavenProjectLicensesIT.java

The `ProjectBuildingRequest` requires a project to be configured. This project is not available by default. The `ProjectBuildingRequest` is mutable, so I did not use the exiting class variable. Instead, I suggest not storing the request but create one as needed. For that purpose, the Maven session is now kept around.
When requiring a request with a project, the existing copy-constructor is new used and a project is configured as needed.
This change also fixes the tests (expecting 0 instead of 1 dependencies). This change has little effect though, as the `MavenProjectLicensesIT` does not actually run.
This fixes #377.

fix: Configure the project for the `ProjectBuildingRequest` being used.

---

license-maven-plugin/pom.xml
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/dependencies/MavenProjectLicensesIT.java
license-maven-plugin/src/test/resources-its/com/mycila/maven/plugin/license/dependencies/MavenProjectLicensesIT/approve/pom.xml
license-maven-plugin/src/test/resources-its/com/mycila/maven/plugin/license/dependencies/MavenProjectLicensesIT/deny/pom.xml
license-maven-plugin/src/test/resources-its/com/mycila/maven/plugin/license/dependencies/MavenProjectLicensesIT/no_dependencies/pom.xml
pom.xml

For a full reasoning of this PR please have a look at the commit message of ccfafe7. This PR is based on PR #473 and contains ac9a205 from that PR.
In short: The changes makes `MavenProjectLIncensesIT` run proper and delegates all the resource copying to the Maven Integration test framework.
- fix: Configure the project for the `ProjectBuildingRequest` being used.
- refactor: Use Maven Integration Test framework to run some integration tests.

refactor: Use Maven Integration Test framework to run some integration tests.

---

license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/LicenseCheckMojo.java
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/AdditionalHeaderMojoTest.java
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/AggregateMojoTest.java
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/CheckTest.java
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/CompleteMojoTest.java
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/MappingMojoTest.java
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/StrictTest.java
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/UpdateMojoTest.java
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/UseDefaultExcludesMojoTest.java
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/UseDefaultMappingMojoTest.java
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/ValidHeaderMojoTest.java

Closes #531.
This changes the `check` mojo default error message from:
```
Some files do not have the expected license header
```
to:
```
Some files do not have the expected license header. Run license:format to update them.
```
Two questions:

Add fix guidance to default `check` error message

---

pom.xml

* Use standard properties to set maven-compiler-plugin's source and target options
* Add the maven.compiler.release property, but only when building with a JDK that supports it, or when building in Eclipse

Use standard properties for maven-compiler-plugin

---

license-maven-plugin-fs/README.md
license-maven-plugin-fs/pom.xml
license-maven-plugin-fs/src/main/java/com/mycila/maven/plugin/license/fs/CopyrightRangeProvider.java
license-maven-plugin-fs/src/main/resources/META-INF/services/com.mycila.maven.plugin.license.PropertiesProvider
license-maven-plugin-fs/src/test/java/com/mycila/maven/plugin/license/fs/CopyrightRangeProviderTest.java
pom.xml

This plugin implements a `PropertiesProvider` bringing properties
`license.fs.copyrightLastYear` and `license.fs.copyrightYears`, very similar to the git plugin does.
Those properties are filled from filesystem last modification timestamp.
This is useful for use with version control systems that preserve filesystem time from commit time, like RTC does.

add license-maven-plugin-fs

---

pom.xml

output is hard to read as it  scrolls off screen buffers due to printing out license data constantly throughout tests.  Instead send test output to logs which makes it easier to read out put and see other issues in our build.

[pom] Redirect surefire out put to file as too noisy

---

license-maven-plugin-fs/pom.xml
license-maven-plugin-git/pom.xml
license-maven-plugin-svn/pom.xml
license-maven-plugin/pom.xml
pom.xml

do this only on linux where its needed to occur.
Currently usage of this makes it hard for contributors as they are blasted with many changes on every run.  Intent here was to run this on GHA only thus fixing so that it no longer runs on windows.  Maybe there is a more friendly determination of GHA but it is set to use ubuntu there.

[reporting] Do not run reports to docs in windows

---

pom.xml

This is for a pom and requires a descriptor to attach.  The parent gets 'No site descriptor found: nothing to attach.'.  And all other modules are not poms so they all fail respectively stating they are not poms.

[pom] Remove maven 2 attach description from site as not used correctly

---

.github/workflows/ci.yaml
.github/workflows/snapshot-report.yml

preparing to move to checkstyle requiring jdk 11.  Removing direct usage of java 8 from builds.  CI will delegate as previously merged making usage of java 8 directly unnecessary now.  The report generation will need to move simply to move and doesn't need a specific version so moved to 17.

Dropping direct usage of jdk 8 in the ci builds and use 17 in report generation

---

license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/Default.java

files are not suitable for licensing and generally skipped

[default] Ignore string template files ('st' and 'stg')

---

pom.xml

Main purpose here is to prevent included libraries from violating jdk requirements of project.  Currently if you set jgit to 6.6.0, it will compile without issue.  It will be caught by our usage tests on java 8, but this will further catch it right away.
Example to see, if you go to the jgit module, bump jgit to 6.6.0.202305301015-r, run a build without this, it works.  After this is added, you will get following
```
[ERROR] Rule 0: org.codehaus.mojo.extraenforcer.dependencies.EnforceBytecodeVersion failed with message:
[ERROR] Found Banned Dependency: org.eclipse.jgit:org.eclipse.jgit:jar:6.6.0.202305301015-r
[ERROR] Use 'mvn dependency:tree' to locate the source of the banned dependencies.
```
Earlier stop is more useful then waiting to make sure IT tests pass.

[pom] Enforce byte code to java 8

---

license-maven-plugin/pom.xml
pom.xml

This is a draft as waiting on #623.  It can otherwise be used to test parent 11 by manually building it locally off that PR noted.

[pom] Move from legacy license configuration to license sets and update parent-pom to 12

---

license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/document/DocumentType.java

proto files use double slash style
[example](https://github.com/tensorflow/tfx/blob/84ce53f0b2773c4592041fc548b4ca654e614b75/tfx/proto/orchestration/execution_invocation.proto)

[docType] Add proto type

---

license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/document/DocumentType.java

They use slashstar_style
[gradle](https://github.com/gradle/gradle/blob/550c50979e64b07da54803d699d036cad23f7fb9/subprojects/performance/src/templates/task-creation/build.gradle)
[kts](https://github.com/JetBrains/kotlin/blob/e9d4de658dd3110c76d7247ea639a2d00f273aef/repo/gradle-build-conventions/buildsrc-compat/src/main/kotlin/java-instrumentation.gradle.kts)
Fixes #631

[documentType] Add .gradle .kts document type

---

license-maven-plugin/pom.xml

moving plexus forwards which includes some maven 4 in plexus xml so maven provided a bridge for plexus xml 3.0.0 to avoid maven 4 apis and thus remain compatible to maven 3.

[pom] Bump plexus utils to 4.0.0 and add plexus xml 3.0.0 override

---

license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/Default.java

Well known editor config file recognised by most IDEs and text editors
https://editorconfig.org/

chore: exclude .editorconfig file by default

---

license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/AbstractLicenseMojo.java

currently plugin shows nothing, to make it clear to users, when skipped, issue message that its been skipped as most plugins do.

[ci] Add info when license plugin is skipped

---

license-maven-plugin-git/src/main/java/com/mycila/maven/plugin/license/git/GitLookup.java
license-maven-plugin-git/src/main/java/com/mycila/maven/plugin/license/git/GitPathResolver.java
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/AbstractLicenseMojo.java
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/HeaderStyle.java
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/LicenseCheckMojo.java
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/LicenseFormatMojo.java
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/LicenseRemoveMojo.java
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/LicenseSet.java
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/PropertiesProvider.java
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/dependencies/AbstractLicensePolicyEnforcer.java
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/dependencies/AggregateLicensePolicyEnforcer.java
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/dependencies/LicensePolicy.java
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/dependencies/MavenProjectLicenses.java
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/header/HeaderDefinition.java
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/header/HeaderParser.java
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/util/resource/ResourceFinder.java

This does clear the main javadoc issues.  There are some bug fixes here and only where javadoc plugin complained to fill in rest of required data on existing javadocs.  This is significantly smaller than original attempt where I had just added docs for everything.  This also does not fix the submodule doc issues but there are far less of those and they can come in later so this is kept to a minimum as needed.  Given there is one deprecated item in here, we may want to further consider removing it now but filled it out anyways.

[docs] Fix some javadoc issues

---

.gitignore
license-maven-plugin-fs/pom.xml
license-maven-plugin-git/pom.xml
license-maven-plugin-git/src/main/java/com/mycila/maven/plugin/license/git/GitLookup.java
license-maven-plugin-svn/pom.xml
license-maven-plugin/pom.xml
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/Default.java
pom.xml

Fixes https://github.com/mathieucarbou/license-maven-plugin/issues/691
There is a lot here, normally I would have ended up splitting things up to smaller pulls but given having to run side by side comparisons with existing build in favor of dropping the parent-pom from the mix, I felt it was easier to just keep all findings together and some of that journey to get here.  You may want to also run side by side comparison to confirm.  
- Before, as known, source was running in both forked and non forked mode.  It now runs exactly as its supposed to and can be on latest version now.
- Maven plugin descriptor and help mojo's were running twice as the naming in parent-pom id and this project were different
- Did not pull forwards any of the OSGI stuff, none of it ran against this project
- Did …

Drop parent pom, fix up some build issues, add new discovery of .checkstyle now being produced in recent Eclipse with personal data

---

.mvn/wrapper/MavenWrapperDownloader.java
.mvn/wrapper/maven-wrapper.properties
mvnw
mvnw.cmd
pom.xml
renovate.json

Renovate file for my fork usage and otherwise entirely ignored.  Maven wrapper updated to 3.3.1.

Update maven wrapper to 3.3.1 and adjustment in renovate tracking file

---

.github/workflows/ci.yaml
license-maven-plugin/pom.xml

See https://maven.apache.org/docs/history.html for maven support requires.

Require maven 3.6.3 along with GHA updates to get mac running java 8 again

---

license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/util/FileUtils.java
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/util/FileUtilsTest.java

Correctly open URLs for reading

---

.mvn/wrapper/maven-wrapper.properties
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/AbstractLicenseMojo.java

changed in maven plugin tools.  maven has long been using jsr330 so the extra annotation was unnecessary.

Update deprecated maven annotatoin to jsr330 ```@Inject```

---

pom.xml

already moved plugin per maven requirements, noticed overall build was still enforced to 3.2.5 or better.

[pom] Require maven 3.6.3 or better to build

---

license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/Default.java

those are auto generated and should not be considered.  some projects use both maven and gradle so this conflicts, so ignore it like we do gradle wrapper.
c

[exclusions] Do not handle .gradle or build directories

---

.mvn/wrapper/MavenWrapperDownloader.java
license-maven-plugin-fs/src/test/java/com/mycila/maven/plugin/license/fs/CopyrightRangeProviderTest.java
license-maven-plugin-git/src/test/java/com/mycila/maven/plugin/license/git/CopyrightAuthorProviderTest.java
license-maven-plugin-git/src/test/java/com/mycila/maven/plugin/license/git/CopyrightRangeProviderTest.java
license-maven-plugin-git/src/test/java/com/mycila/maven/plugin/license/git/GitLookupTest.java
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/util/resource/ResourceFinder.java
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/header/HeaderSourceTest.java
license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/util/resource/ResourceFinderTest.java

after java 11, Paths.get is just calling Path.of
See https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/file/Path.html#of(java.lang.String,java.lang.String...)

[java11] Use Path.of instead of Paths.get

---

license-maven-plugin/pom.xml
license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/document/DocumentFactory.java

plexus xml no longer needs to be in the pom.  It was there because maven leaked maven 4 into the maven 3 code.  They since fixed the issue.

Use less of plexus and no longer need to override plexus xml

---

license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/Default.java
pom.xml

- Sorted section including pom.xml items, added tag and next entries
- Add .vscode to ignores
- Removed from internal license plugin exclusions .checkstyle and release-pom.xml as already ignored.

Add to default exclusion and cleanup pom on exclusions already in core releases

---

.github/workflows/ci.yaml
.github/workflows/snapshot-report.yml

Git expects all readable files have proper end of file line marker to assist with diffs.
Some info on this is here https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log.
The largest contributor to this problem on the repo right now is the docs folder.
In order to properly fix files we really care about, we need to ensure the docs that are integrated into the overall build files adhere to this standard.
Note: This was not tested on GHA but is a command used locally by me for number of years.  It may need a bit of tweaking in case expected syntax is off a bit on translation from git alias to a call on github.  Not sure the best way to test this otherwise then see if it works.  I've otherwise ran the command from a git alias locally and just …

[gha] Make sure we cache maven (and sort) and make sure docs are proper EOF marked

---

.github/workflows/ci.yaml
license-maven-plugin/pom.xml
pom.xml

- Added mockito bom to ensure its usage of byte buddy doesn't get manipulated by another other libs so higher jdks work without issues.
- Drop jdk 22 on build matrix
- Add jdk 23 on build matrix
- Add jdk 24-ea on build matrix
- Do not care about byte compatibility for 'test' or 'provided' scope as neither affects consumers
- Fix javadoc link to java 11 fixing jdk 23+

Build cleanup items
